<h1> Section 4: Numpy

<h2> Numpy Arrays
   

<h3>Built-in functions

In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]

In [3]:
type(mylist)

list

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
mylist

[1, 2, 3]

In [6]:
myarr = np.array(mylist)

In [7]:
myarr

array([1, 2, 3])

In [8]:
type(myarr)

numpy.ndarray

In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
np.arange(0,101,20) 
# Build an array from 0 to 101, start at 0, spaces of 20, 101 not included

array([  0,  20,  40,  60,  80, 100])

In [30]:
np.zeros(5) 
# 0. just indicates a floating number

array([0., 0., 0., 0., 0.])

In [29]:
np.zeros((5,5)) 
# 2 dimensional array, first number is rows, second is columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
np.linspace(0,10,3) 
# gets 3 linear spaces in interval from 0 to 10, 10 included

array([ 0.,  5., 10.])

In [34]:
np.linspace(0,10,11) 
# As the stop point is included, to return int numbers, must add 1 to space

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [173]:
np.eye(5) # Identity matrix, Rows == Coluns, not much used

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

<h3>Random distributions of data

In [40]:
np.random.rand(2) # Random number from 0 to 1, 2 is the quantity

array([0.46239677, 0.65149006])

In [41]:
np.random.rand(5,2) 
# Random numbers form 0 to 1, first is number rows, second is number of columns

array([[0.73334331, 0.1403903 ],
       [0.78149979, 0.37115766],
       [0.88580977, 0.45782894],
       [0.47139803, 0.67668631],
       [0.71959212, 0.86581347]])

In [175]:
np.random.randn(10) 
# Returns a standard normal distribution numbers, around zero

array([-0.7033438 , -2.13962066, -0.62947496,  0.59772047,  2.55948803,
        0.39423302,  0.12221917, -0.51543566, -0.60025385,  0.94743982])

In [45]:
np.random.randn(5,2)

array([[-0.08607037,  0.88554251],
       [ 1.52079187, -0.20242658],
       [-1.32559335,  0.9323551 ],
       [-0.60494713,  0.10309854],
       [-1.13877314, -0.28465439]])

In [47]:
np.random.randint(0,101,5)
# Returns 5 random int numbers from 0 to 100, 101 not inclusive

array([46, 62, 29, 74, 98])

In [48]:
np.random.randint(0,101,(4,5))
# Returns a 4 by 5 array of random int numbers from 0 to 100, 101 not inclusive

array([[80, 34,  3, 74, 48],
       [ 8, 42, 11, 80, 29],
       [83, 95, 50, 87, 82],
       [56, 36, 48, 17, 15]])

In [54]:
np.random.seed(42) # This seed makes the random numbers to keep the same
np.random.rand(4) # This function will take the seed into account

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [58]:
# Testing seed
np.random.seed(30)
np.random.rand(4)

array([0.64414354, 0.38074849, 0.66304791, 0.16365073])

In [59]:
# Testing seed
np.random.rand(4)

array([0.96260781, 0.34666184, 0.99175099, 0.2350579 ])

In [60]:
# Testing seed
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

<h3>Key attributes and method calls of Numpy arrays

In [61]:
arr = np.arange(0,25)

In [63]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [64]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [66]:
arr.reshape(5,4)
# Returns an error, not possible to fit 20(5*4) elements on a 25 array

ValueError: cannot reshape array of size 25 into shape (5,4)

In [67]:
ranarr = np.random.randint(0,101,10)

In [68]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [69]:
ranarr.max()

99

In [70]:
ranarr.min()

2

In [71]:
ranarr.argmax()

5

In [72]:
ranarr.argmin()

7

In [73]:
ranarr.dtype

dtype('int32')

In [75]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [76]:
arr.shape

(25,)

In [77]:
arr = arr.reshape(5,5)

In [78]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [86]:
arr.shape

(5, 5)

In [87]:
teste1 = arr.reshape(1,25)

In [88]:
teste2 = arr.reshape(25,1)

In [89]:
teste1.shape

(1, 25)

In [90]:
teste2.shape

(25, 1)

<h2> Indexing and Selection

<h3>Grabbing single element

In [91]:
arr = np.arange(0,11)

In [92]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
arr[8]

8

<h3>Grabbing a slice of elements

In [94]:
arr[1:5]

array([1, 2, 3, 4])

In [95]:
arr[:5]

array([0, 1, 2, 3, 4])

In [97]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

<h3>Broadcasting selections

In [98]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
arr[0:5] = 100

In [101]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [102]:
arr = np.arange(0,11)

In [104]:
slice_of_arr = arr[0:5]
# This slice method, just points to the original array

In [105]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [106]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
slice_of_arr[:] = 99
# So modifying the sliced array...

In [108]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [112]:
arr
# Also modify the original array

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [119]:
arr_copy = arr.copy()
# Create a copy of the original array before slice, to prevent to change the original

In [116]:
arr_copy[:] = 100

In [117]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [118]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

<h3>Indexing and selection in 2-dimensions

In [120]:
arr_2d = np.array([[5,10,15],[20,25,30],[30,40,45]])

In [121]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [30, 40, 45]])

In [122]:
arr_2d.shape

(3, 3)

In [123]:
arr_2d[0]

array([ 5, 10, 15])

In [125]:
arr_2d[1][1]

25

In [127]:
arr_2d[1,1]

25

In [128]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

<h3>Conditional Selection

In [131]:
arr = np.arange(1,11)

In [132]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [133]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [138]:
bool_arr = arr>4
# do a comparison to generate a boolean array

In [139]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [140]:
arr[bool_arr]
# Using boolean array to filter original array

array([ 5,  6,  7,  8,  9, 10])

In [142]:
arr[arr>4]
# Make the same filter, using the condition direct on the array

array([ 5,  6,  7,  8,  9, 10])

<h2> Numpy Operators

<h2>Arithmetics

In [143]:
arr = np.arange(0,10)

In [144]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [145]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [147]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [148]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [149]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [150]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [151]:
arr / arr 

C:\Users\PC\AppData\Local\Temp/ipykernel_10940/2663351161.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [152]:
1 / 0 # Error

ZeroDivisionError: division by zero

In [153]:
1 / arr[0] # Warning

C:\Users\PC\AppData\Local\Temp/ipykernel_10940/2460598279.py:1: RuntimeWarning: divide by zero encountered in long_scalars
  1 / arr[0]


inf

In [154]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [155]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [156]:
np.log(arr) # Division by zero Warning

C:\Users\PC\AppData\Local\Temp/ipykernel_10940/2912737015.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr) # Division by zero Warning


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [158]:
arr.sum()

45

In [159]:
arr.mean()

4.5

In [160]:
arr.max()

9

In [161]:
arr.var()

8.25

In [162]:
arr.std()

2.8722813232690143

In [164]:
arr2d = np.arange(0,25).reshape(5,5)

In [165]:
arr2d.shape

(5, 5)

In [166]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [167]:
arr2d.sum()

300

In [171]:
arr2d.sum(axis=0) 
# Axis 0, means to sum accros the rows, or total for each column
# Index 0 of shape means rows

array([50, 55, 60, 65, 70])

In [172]:
arr2d.sum(axis=1) 
# Axis 0, means to sum accros the columns, or total for each row
# Index 1 of shape means columns

array([ 10,  35,  60,  85, 110])